/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.swanmusic.ui;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import lab8_new1.SendMail;
import java.util.Random;

/**
/**
 *
 * @author phuon
 */
public class quenmatkhauJDialog extends javax.swing.JDialog {
int otp;
    /**
     * Creates new form quenmatkhauJDialog
     */
    public quenmatkhauJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }
    
        void init(){
        this.setSize(1242,682);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel1 = new com.swanmusic.swing.Panel();
        jLabel2 = new javax.swing.JLabel();
        txtMaXM = new javax.swing.JPasswordField();
        lblNhapMKMoi = new javax.swing.JLabel();
        btnDangNhap = new javax.swing.JButton();
        lblDT2 = new javax.swing.JLabel();
        lblDT = new javax.swing.JLabel();
        lblRanhGioi = new javax.swing.JLabel();
        btnDatLai = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtNhapMKMoi1 = new javax.swing.JPasswordField();
        btnGuima = new javax.swing.JButton();
        txtEmail = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        panel1.setBackground(new java.awt.Color(255, 201, 221));
        panel1.setToolTipText("");
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/swanmusic/img/logoswan_ok.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 390, -1));

        txtMaXM.setBackground(new java.awt.Color(255, 145, 185));
        txtMaXM.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panel1.add(txtMaXM, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 300, 220, 50));

        lblNhapMKMoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNhapMKMoi.setForeground(new java.awt.Color(255, 255, 255));
        lblNhapMKMoi.setText("Nhập mật khẩu mới:");
        panel1.add(lblNhapMKMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, -1, -1));

        btnDangNhap.setBackground(new java.awt.Color(255, 145, 185));
        btnDangNhap.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDangNhap.setForeground(new java.awt.Color(255, 255, 255));
        btnDangNhap.setText("Đăng nhập");
        btnDangNhap.setBorder(null);
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });
        panel1.add(btnDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 510, 460, 60));

        lblDT2.setForeground(new java.awt.Color(255, 255, 255));
        lblDT2.setText("-----------------------------------");
        panel1.add(lblDT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 470, 170, -1));

        lblDT.setForeground(new java.awt.Color(255, 255, 255));
        lblDT.setText("-----------------------------------");
        panel1.add(lblDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 470, 190, -1));

        lblRanhGioi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRanhGioi.setForeground(new java.awt.Color(255, 255, 255));
        lblRanhGioi.setText("Hoặc tiếp tục với");
        panel1.add(lblRanhGioi, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 470, -1, -1));

        btnDatLai.setBackground(new java.awt.Color(255, 145, 185));
        btnDatLai.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDatLai.setForeground(new java.awt.Color(255, 255, 255));
        btnDatLai.setText("Đặt lại mật khẩu");
        btnDatLai.setBorder(null);
        btnDatLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatLaiActionPerformed(evt);
            }
        });
        panel1.add(btnDatLai, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 460, 60));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("QUÊN MẬT KHẨU");
        panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, -1, -1));

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("Email:");
        panel1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, -1, -1));

        txtNhapMKMoi1.setBackground(new java.awt.Color(255, 145, 185));
        txtNhapMKMoi1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panel1.add(txtNhapMKMoi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 220, 460, 50));

        btnGuima.setBackground(new java.awt.Color(255, 75, 141));
        btnGuima.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuima.setForeground(new java.awt.Color(255, 255, 255));
        btnGuima.setText("Gửi mã");
        btnGuima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuimaActionPerformed(evt);
            }
        });
        panel1.add(btnGuima, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 300, 160, 50));

        txtEmail.setBackground(new java.awt.Color(255, 145, 185));
        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, 460, 50));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1242, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(32, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 681, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(48, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuimaActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            Properties p = new Properties();
            p.put("mail.smtp.auth", "true");
            p.put("mail.smtp.starttls.enable", "true");
            p.put("mail.smtp.host", "smtp.gmail.com");
            p.put("mail.smtp.port", 587);
            // -----
            final String accountName = "tranhtbts00531@fpt.edu.vn";
            final String accountPassword = "hjhs sujj qdpf qwkp";
            Session s = Session.getInstance(p,
                    new javax.mail.Authenticator() {
                        protected PasswordAuthentication getPasswordAuthentication() {
                            return new PasswordAuthentication(accountName, accountPassword);
                        }
                    });
            // --------
            Random random=new Random();
            int min =1000;
             int max =9999;
             otp=random.nextInt(max-min)+min;
            String from = "tranhtbts00531@fpt.edu.vn";
            String to = txtEmail.getText();
            String body =String.valueOf(otp);
            Message msg = new MimeMessage(s);
            // gán giá trị cho các thuộc tính của đối tượng msg
            msg.setFrom(new InternetAddress(from));
            msg.setRecipients(Message.RecipientType.TO, InternetAddress.parse(to));
            msg.setText(body);
            // -----------
            Transport.send(msg); //

            JOptionPane.showMessageDialog(null, "Mail was sent successfully.", "Message",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } catch (MessagingException ex) {
            Logger.getLogger(SendMail.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGuimaActionPerformed

    private void btnDatLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatLaiActionPerformed
        // TODO add your handling code here:
         int otp2=Integer.parseInt(txtMaXM.getText());
        if(otp==otp2)
        {
            JOptionPane.showMessageDialog(this, "Mã xác minh trùng khớp");
        }
        else{
              JOptionPane.showMessageDialog(this, "Mã xác minh không trùng khớp");
        }
          try {
            String url = "jdbc:sqlserver://localhost:1433;DatabaseName=SWAN;encrypt=false";
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection(url, "sa", "");
            PreparedStatement ps = con.prepareCall("update TAIKHOAN set MATKHAU = ? where EMAIL = ?");
           
            ps.setString(2, txtEmail.getText());
            ps.setString(1, txtNhapMKMoi1.getText());
         
            int kq = ps.executeUpdate();
            if (kq == 1) {
                JOptionPane.showMessageDialog(this, "Cập nhật thành công");
            } else {
                JOptionPane.showMessageDialog(this, "Cập nhật thất bại");
            }
            ps.close();
            con.close();
     
        } catch (Exception e) {
            e.printStackTrace();
        }
           
    }//GEN-LAST:event_btnDatLaiActionPerformed

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new dangnhapJDialog(null,true).setVisible(true);
    }//GEN-LAST:event_btnDangNhapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quenmatkhauJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quenmatkhauJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quenmatkhauJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quenmatkhauJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                quenmatkhauJDialog dialog = new quenmatkhauJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JButton btnDatLai;
    private javax.swing.JButton btnGuima;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDT;
    private javax.swing.JLabel lblDT2;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNhapMKMoi;
    private javax.swing.JLabel lblRanhGioi;
    private com.swanmusic.swing.Panel panel1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtMaXM;
    private javax.swing.JPasswordField txtNhapMKMoi1;
    // End of variables declaration//GEN-END:variables
}
