/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.swanmusic.User;
import com.swanmusic.User.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.Image;
import javax.swing.JFileChooser;
import javax.swing.*;
import com.swanmusic.entity.Account;
/**
 *
 * @author phuon
 */
public class dangky extends javax.swing.JDialog {
public static Home main;
//public static Main main;
    boolean forgot = false;
//    dangnhapJDialog dn = new dangnhapJDialog(main, forgot);
    
    public dangky(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }
          ArrayList<Account> list = new ArrayList();
        void init(){
        this.setSize(1242,682);
        this.setLocationRelativeTo(null);

    }
        public void load_data() {
        list.clear();
        try {
            String url = "jdbc:sqlserver://localHost:1433;DatabaseName=SWAN;encrypt=true;trustServerCertificate=true";
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection(url, "sa", "");
            PreparedStatement ps = con.prepareCall("select * from  TAIKHOAN");
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                Account mu = new Account();
                mu.setTENTK(rs.getString("TENTAIKHOAN"));
                mu.setMatkhau(rs.getString("MATKHAU"));
                 boolean IsRole = rs.getBoolean("VAITRO"); 
                mu.setVaiTro(IsRole);
                mu.setEmail(rs.getString("EMAIL"));
                   mu.setSODIENTHOAI(rs.getString("SODIENTHOAI"));
                list.add(mu);
            }
//            DefaultTableModel model = (DefaultTableModel) tbl.getModel();
//            model.setRowCount(0);
            rs.close();
            ps.close();
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nenden = new javax.swing.JPanel();
        panel1 = new com.swanmusic.swing.Panel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        lblPass = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        btnDangNhap = new javax.swing.JButton();
        lblDT2 = new javax.swing.JLabel();
        lblDT = new javax.swing.JLabel();
        lblRanhGioi = new javax.swing.JLabel();
        btnDangKy = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblNhaplaiMK = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNhaplaiMK = new javax.swing.JPasswordField();
        lblEmail = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        nenden.setBackground(new java.awt.Color(255, 255, 255));
        nenden.setForeground(new java.awt.Color(255, 255, 255));
        nenden.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setBackground(new java.awt.Color(255, 201, 221));
        panel1.setToolTipText("");
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/swanmusic/img/logoswan_ok.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 390, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 196, 235));
        jLabel6.setText("Email");
        jLabel6.setPreferredSize(new java.awt.Dimension(85, 15));
        panel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 340, 100, 30));

        txtEmail.setBackground(new java.awt.Color(255, 145, 185));
        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtEmail.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtEmailCaretUpdate(evt);
            }
        });
        panel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, 460, 50));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 196, 235));
        jLabel4.setText("Mật Khẩu");
        panel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, 100, 30));

        txtPass.setBackground(new java.awt.Color(255, 145, 185));
        txtPass.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPass.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtPassCaretUpdate(evt);
            }
        });
        panel1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, 460, 50));

        lblPass.setBackground(new java.awt.Color(255, 255, 255));
        lblPass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPass.setForeground(new java.awt.Color(255, 255, 255));
        lblPass.setText("Mật khẩu:");
        panel1.add(lblPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, -1, -1));

        lblName.setBackground(new java.awt.Color(255, 255, 255));
        lblName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Tên tài khoản:");
        panel1.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, -1, -1));

        btnDangNhap.setBackground(new java.awt.Color(255, 145, 185));
        btnDangNhap.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDangNhap.setForeground(new java.awt.Color(255, 255, 255));
        btnDangNhap.setText("Đăng nhập");
        btnDangNhap.setBorder(null);
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });
        panel1.add(btnDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 540, 460, 60));

        lblDT2.setBackground(new java.awt.Color(255, 255, 255));
        lblDT2.setForeground(new java.awt.Color(255, 255, 255));
        lblDT2.setText("-----------------------------------");
        panel1.add(lblDT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 500, 170, -1));

        lblDT.setBackground(new java.awt.Color(255, 255, 255));
        lblDT.setForeground(new java.awt.Color(255, 255, 255));
        lblDT.setText("-----------------------------------");
        panel1.add(lblDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 500, 190, -1));

        lblRanhGioi.setBackground(new java.awt.Color(255, 255, 255));
        lblRanhGioi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRanhGioi.setForeground(new java.awt.Color(255, 255, 255));
        lblRanhGioi.setText("Hoặc tiếp tục với");
        panel1.add(lblRanhGioi, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 500, -1, -1));

        btnDangKy.setBackground(new java.awt.Color(255, 145, 185));
        btnDangKy.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDangKy.setForeground(new java.awt.Color(255, 255, 255));
        btnDangKy.setText("Đăng ký");
        btnDangKy.setBorder(null);
        btnDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangKyActionPerformed(evt);
            }
        });
        panel1.add(btnDangKy, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 420, 460, 60));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ĐĂNG KÝ");
        panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, -1, -1));

        lblNhaplaiMK.setBackground(new java.awt.Color(255, 255, 255));
        lblNhaplaiMK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNhaplaiMK.setForeground(new java.awt.Color(255, 255, 255));
        lblNhaplaiMK.setText("Nhập lại mật khẩu:");
        panel1.add(lblNhaplaiMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 196, 235));
        jLabel5.setText("Nhập lại mật khẩu");
        jLabel5.setPreferredSize(new java.awt.Dimension(85, 15));
        panel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 170, 30));

        txtNhaplaiMK.setBackground(new java.awt.Color(255, 145, 185));
        txtNhaplaiMK.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNhaplaiMK.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtNhaplaiMKCaretUpdate(evt);
            }
        });
        panel1.add(txtNhaplaiMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 250, 460, 50));

        lblEmail.setBackground(new java.awt.Color(255, 255, 255));
        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("Email:");
        panel1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 310, -1, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 196, 235));
        jLabel7.setText("Tên tài khoản");
        panel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, -1, -1));

        txtName.setBackground(new java.awt.Color(255, 145, 185));
        txtName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtName.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtNameCaretUpdate(evt);
            }
        });
        panel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, 460, 50));

        nenden.add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 8, 1210, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nenden, javax.swing.GroupLayout.DEFAULT_SIZE, 1242, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nenden, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtNameCaretUpdate
        // TODO add your handling code here:
             if (!txtName.getText().equals("")) {
            jLabel7.setText("");
        } else {
            jLabel7.setText("Tên tài khoản");
        }
                    
    }//GEN-LAST:event_txtNameCaretUpdate

    private void txtPassCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtPassCaretUpdate
        // TODO add your handling code here:
           if (!txtPass.getText().equals("")) {
            jLabel4.setText("");
        } else {
            jLabel4.setText("Mật khẩu");
        }
    }//GEN-LAST:event_txtPassCaretUpdate

    private void txtNhaplaiMKCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtNhaplaiMKCaretUpdate
        // TODO add your handling code here:
        if (!txtNhaplaiMK.getText().equals("")) {
            jLabel5.setText("");
        } else {
            jLabel5.setText("Nhập lại mật khẩu");
        }
    }//GEN-LAST:event_txtNhaplaiMKCaretUpdate

    private void txtEmailCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtEmailCaretUpdate
        // TODO add your handling code here:
         if (!txtEmail.getText().equals("")) {
            jLabel6.setText("");
        } else {
            jLabel6.setText("Email");
        }
    }//GEN-LAST:event_txtEmailCaretUpdate

    private void btnDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangKyActionPerformed
        // TODO add your handling code here:
          String account = txtName.getText();
        String password = txtPass.getText();
        String checkpass = txtNhaplaiMK.getText();
        String email = txtEmail.getText();
        if (account.isEmpty() || password.isEmpty() || checkpass.isEmpty() ||email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin!");
        } else if (!password.equals(checkpass)) {
            JOptionPane.showMessageDialog(this, "Mật khẩu không khớp!");
        } else {
                try {
                String url = "jdbc:sqlserver://localHost:1433;DatabaseName=SWAN;encrypt=true;trustServerCertificate=true";
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                Connection con = DriverManager.getConnection(url, "sa", "");
                PreparedStatement ps = con.prepareCall("insert into TAIKHOAN (TENTAIKHOAN,MATKHAU,VAITRO,EMAIL) VALUES (?,?,'0',?)");
                ps.setString(1, txtName.getText());
                ps.setString(2, txtPass.getText());
                ps.setString(3, txtEmail.getText());
                int kq = ps.executeUpdate();
                if (kq == 1) {
                    JOptionPane.showMessageDialog(this, "Lưu thành công");
                } else {
                    JOptionPane.showMessageDialog(this, "Lưu không thành công");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_btnDangKyActionPerformed

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new com.swanmusic.User.Dangnhap(null,true).setVisible(true);
    }//GEN-LAST:event_btnDangNhapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dangky.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dangky.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dangky.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dangky.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dangky dialog = new dangky(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangKy;
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblDT;
    private javax.swing.JLabel lblDT2;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNhaplaiMK;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblRanhGioi;
    private javax.swing.JPanel nenden;
    private com.swanmusic.swing.Panel panel1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtNhaplaiMK;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables
}
